################################################################
# Affiliated packages                                          #
################################################################

# We also have astropy in this channel
- name: astropy

- name: glueviz
  # list only the name of packages that have conda-forge build, no version
  # or other info required

- name: astropy-healpix

- name: astroquery

- name: sncosmo

  # # Version should match the version on PyPI. Versions that could be
  # # interpereted as numbers (e.g. 0.1) should be enclosed in quotes.
  # version: 1.5.1

  # # conda builds disable downloading, but astropy-helpers is typically
  # # configured to try to autoupdate during install of affiliated
  # # packages. Set to true if the package uses astropy-helpers and
  # # auto-update and the --offline flag will be passed to setup.py.
  # setup_options: '--offline'   # Defaults to false if omitted.

  # # If the package contains compiled extensions that link to numpy this
  # # must be set to true to ensure the package is built properly.
  # # If in doubt, set it to true...though it should *always* be false
  # # for a pure python package.
  # numpy_compiled_extensions: true   # Defaults to false if omitted.

  # # Some packages can only be built for specific versions of python but
  # # setup.py often does not contain those restrictions (and conda skeleton
  # # ignores it if present), so list restrictions on python version here.

  # # python: '>2.6|>=3.4'  # if omitted, no restriction on python builds.

- name: pydl

- name: ccdproc

- name: wcsaxes

- name: gammapy

- name: pyvo

- name: photutils

- name: spherical-geometry

- name: APLpy

- name: pyavm

- name: specutils

- name: imexam

- name: gwcs

- name: asdf

- name: pyregion

- name: astroML

- name: ginga

- name: naima

- name: reproject

- name: astroplan

- name: python-cpl

- name: astroscrappy

- name: omnifit

- name: maltpynt

- name: spectral-cube

- name: halotools

- name: regions

- name: cluster-lensing

- name: gala

- name: galpy

- name: hips

- name: dust_extinction

- name: hendrics

- name: stingray

- name: baseband

- name: corral-pipeline

- name: pyspeckit

- name: synphot

- name: linetools

- name: einsteinpy

- name: feets

- name: ligo.skymap

- name: marxs

- name: statmorph

- name: agnpy

- name: astroalign

################################################################
# Infrastructure packages                                      #
################################################################

- name: pytest-astropy

- name: pytest-openfiles

- name: pytest-doctestplus

- name: pytest-remotedata

- name: pytest-astropy-header

- name: pytest-filter-subpackage

- name: sphinx-astropy

- name: sphinx-automodapi

- name: astropy-sphinx-theme

- name: pyerfa

################################################################
# These are additional dependencies of some of the affiliated  #
# packages we build above                                      #
################################################################

- name: pyephem

# lmfit is required for omnifit
- name: lmfit

- name: iminuit

- name: emcee

- name: corner

- name: pytest-mpl

- name: pytest-arraydiff

- name: extinction

- name: poliastro

# sadisplay is required for corral-pipeline
- name: sadisplay

# sphinx-gallery is required for sphinx-astropy
- name: sphinx-gallery

# dependency of pyvo
- name: python-mimeparse

# test dependency for astropy
- name: jplephem

# Now required for all required packages (as of October 2020)
- name: python_abi
