################################################################
# Affiliated packages                                          #
################################################################

# astroscrappy has a recipe template
- name: astroscrappy
  version: '1.0.5'
  setup_options: '--offline'
  numpy_compiled_extensions: true
