################################################################
# Affiliated packages                                          #
################################################################

# astropy-helpers has a recipe template
- name: astropy-helpers
  version: 2.0

- name: glueviz
  # list only the name of packages that have conda-forge build, no version
  # or other info required

- name: astroquery

- name: sncosmo

  # # Version should match the version on PyPI. Versions that could be
  # # interpereted as numbers (e.g. 0.1) should be enclosed in quotes.
  # version: 1.5.1

  # # conda builds disable downloading, but astropy-helpers is typically
  # # configured to try to autoupdate during install of affiliated
  # # packages. Set to true if the package uses astropy-helpers and
  # # auto-update and the --offline flag will be passed to setup.py.
  # setup_options: '--offline'   # Defaults to false if omitted.

  # # If the package contains compiled extensions that link to numpy this
  # # must be set to true to ensure the package is built properly.
  # # If in doubt, set it to true...though it should *always* be false
  # # for a pure python package.
  # numpy_compiled_extensions: true   # Defaults to false if omitted.

  # # Some packages can only be built for specific versions of python but
  # # setup.py often does not contain those restrictions (and conda skeleton
  # # ignores it if present), so list restrictions on python version here.

  # # python: '>2.6|>=3.4'  # if omitted, no restriction on python builds.

- name: pydl

# montage-wrapper has a recipe template
- name: montage-wrapper
  version: 0.9.9
  setup_options: '--offline'
  numpy_compiled_extensions: false

- name: ccdproc

- name: wcsaxes

- name: gammapy

- name: pyvo

- name: photutils

- name: spherical-geometry

- name: APLpy

- name: specutils

- name: imexam

- name: gwcs

- name: asdf

- name: pyregion

- name: astroML

- name: ginga

- name: naima

- name: reproject

- name: astroplan

- name: python-cpl

- name: astroscrappy

- name: omnifit

- name: maltpynt

- name: spectral-cube

- name: halotools

- name: regions

- name: cluster-lensing

- name: astro-gala

- name: galpy

################################################################
# These are additional dependencies of some of the affiliated  #
# packages we build above                                      #
################################################################

- name: pyephem

- name: hgtools
  version: '6.3'

# lmfit is required for omnifit
- name: lmfit

- name: iminuit

- name: emcee

- name: corner

- name: pytest-mpl

- name: pytest-arraydiff
  version: 0.1

- name: extinction
