################################################################
# Affiliated packages                                          #
################################################################

# astropy-helpers has a recipe template
- name: astropy-helpers
  version: 1.3.1

- name: glueviz
  # list only the name of packages that have conda-forge build, no version
  # or other info required

- name: astroquery

# sncosmo has a recipe template
- name: sncosmo
  # Version should match the version on PyPI. Versions that could be
  # interpereted as numbers (e.g. 0.1) should be enclosed in quotes.
  version: 1.5.1

  # conda builds disable downloading, but astropy-helpers is typically
  # configured to try to autoupdate during install of affiliated
  # packages. Set to true if the package uses astropy-helpers and
  # auto-update and the --offline flag will be passed to setup.py.
  setup_options: '--offline'   # Defaults to false if omitted.

  # If the package contains compiled extensions that link to numpy this
  # must be set to true to ensure the package is built properly.
  # If in doubt, set it to true...though it should *always* be false
  # for a pure python package.
  numpy_compiled_extensions: true   # Defaults to false if omitted.

  # Some packages can only be built for specific versions of python but
  # setup.py often does not contain those restrictions (and conda skeleton
  # ignores it if present), so list restrictions on python version here.

  # python: '>2.6|>=3.4'  # if omitted, no restriction on python builds.

- name: pydl
  version: 0.5.4
  setup_options: '--offline'
  numpy_compiled_extensions: false

# montage-wrapper has a recipe template
- name: montage-wrapper
  version: 0.9.8
  setup_options: '--offline'
  numpy_compiled_extensions: false
  python: '<3.6*'

# ccdproc has a recipe template
- name: ccdproc
  version: 1.2.0
  setup_options: '--offline'
  numpy_compiled_extensions: false

- name: wcsaxes

- name: gammapy
  version: '0.6'
  setup_options: '--offline'
  numpy_compiled_extensions: false
  include_extras: false

- name: pyvo
  version: 0.6.0
  setup_options: '--offline'
  numpy_compiled_extensions: false

- name: photutils
  version: '0.3.2'
  setup_options: '--offline'
  numpy_compiled_extensions: false

- name: spherical-geometry
  version: 1.0.6
  setup_options: '--offline'
  numpy_compiled_extensions: false
  python: '<3.5.2'
  excluded_platforms:
      - 'win-64'

# APLpy currently has a recipe template
- name: APLpy
  version: '1.1.1'
  setup_options: '--offline'

- name: specutils
  version: '0.2.2'
  setup_options: '--offline'
  numpy_compiled_extensions: false

# imexam has a recipe template
- name: imexam
  version: 0.7.1
  setup_options: '--offline'
  numpy_compiled_extensions: false

- name: gwcs
  version: 0.7
  setup_options: '--offline'
  numpy_compiled_extensions: false

# asdf has a recipe template
- name: asdf
  version: 1.2.1
  setup_options: '--offline'
  numpy_compiled_extensions: false

- name: pyregion
  version: 1.2
  setup_options: '--offline'
  numpy_compiled_extensions: true

# astroML has a recipe template
- name: astroML
  version: '0.3'
  python: '>=2.6|>=3.3'

- name: ginga
  version: 2.6.2
  numpy_compiled_extensions: false
  python: '>2.6'
  setup_options: '--offline'

# naima has a recipe template
- name: naima
  version: '0.8'
  setup_options: '--offline'
  numpy_compiled_extensions: false

- name: reproject

- name: astroplan
  version: '0.2.1'
  setup_options: '--offline'
  numpy_compiled_extensions: false
  include_extras: true

# python-cpl has a recipe template for now
- name: python-cpl
  version: '0.7.2'

# astroscrappy has a recipe template
- name: astroscrappy
  version: '1.0.5'
  setup_options: '--offline'
  numpy_compiled_extensions: true

- name: omnifit
  version: '0.2.1'
  setup_options: '--offline'
  python: '<3.5.2'

# maltpynt does not seem to actually update astropy_helpers during setup.
- name: maltpynt
  version: '2.0'
  setup_options: '--offline'
  numpy_compiled_extensions: false
  python: '<3.5.2'

- name: spectral-cube
  version: '0.4.0'
  setup_options: '--offline'

- name: halotools
  version: '0.4'
  setup_options: '--offline'
  python: '>=2.7'
  excluded_platforms:
      - 'win-64'

- name: regions
  version: '0.2'
  setup_options: '--offline'
  include_extras: false

# cluster-lensing has a recipe template
- name: cluster-lensing
  version: 0.1.2
  excluded_platforms:
      - 'win-64'

- name: astro-gala
  version: '0.1.3'
  setup_options: '--offline'
  excluded_platforms:
      - 'win-64'

################################################################
# These are additional dependencies of some of the affiliated  #
# packages we build above                                      #
################################################################

- name: pyephem
  version: 3.7.6.0
  python: '<3.6*'

- name: hgtools
  version: '6.3'

# lmfit is required for omnifit
- name: lmfit

- name: iminuit
  version: 1.2

- name: emcee

- name: corner

- name: pytest-mpl

- name: pytest-arraydiff
  version: 0.1

- name: extinction
