# Needs recipe template to:
#
# + Add astropy, numpy, cython as dependencies.
# + Add numpy x.x to pin numpy version.
# + Remove a test and a build instruction for creating an entry point left
#   over from the package template.
package:
  name: astroscrappy
  version: "{{version}}"

source:
  fn: astroscrappy-{{version}}.tar.gz
  url: https://pypi.python.org/packages/source/a/astroscrappy/astroscrappy-{{version}}.tar.gz
  md5: {{md5}}
  patches:
   # List any patch files here
    - windows_patch.diff [win]

requirements:
  build:
    - python
    - setuptools
    - astropy
    - cython
    - numpy x.x
    - numpy >=1.9

  run:
    - python
    - astropy
    - numpy x.x
    - numpy >=1.9

test:
  # Python imports
  imports:
    - astroscrappy
    - astroscrappy.tests
    - astroscrappy.utils

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    # - astropy-package-template-example --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/astropy/astroscrappy
  license: BSD
  summary: 'Speedy Cosmic Ray Annihilation Package in Python'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
