on:
  push:
    branches:
      - main
  schedule:
    # Run once a day at 22:14 UTC
    - cron: '14 22 * * *'

jobs:
  copy_packages:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938  # v4.2.0

    - uses: conda-incubator/setup-miniconda@a4260408e20b96e80095f42ff7f1a15b27dd94ca  # v3.0.4
      with:
        auto-update-conda: true
        python-version: 3.8

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        conda install anaconda-client

    - name: Perform copy
      env:
        BINSTAR_TOKEN: ${{ secrets.BINSTAR_TOKEN }}
      shell: bash -l {0}
      run: |
        git clone https://github.com/glue-viz/conda-sync.git
        mv conda-sync/sync.py .
        conda info -a
        python drive_copy.py
